### ISSUE TITLE
BaseEmailMessage error

### ISSUE THREAD

**Issue by zykys** [treyhunner/django-email-log#46]
hello everyone.
I am faced with the following problem. When I try to send an email, I get an error:

Internal Server Error: /api/auth/users/
Traceback (most recent call last):
  File "D:\dev\python\test\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\python\test\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\python\test\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\python\test\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\python\test\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\python\test\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\dev\python\test\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\dev\python\test\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\python\test\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "D:\dev\python\test\venv\Lib\site-packages\djoser\views.py", line 140, in perform_create
    settings.EMAIL.activation(self.request, context).send(to)
  File "D:\dev\python\test\venv\Lib\site-packages\templated_mail\mail.py", line 78, in send
    super(BaseEmailMessage, self).send(*args, **kwargs)
  File "D:\dev\python\test\venv\Lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\python\test\venv\Lib\site-packages\email_log\backends.py", line 43, in send_messages
    num_sent += message.send()
                ^^^^^^^^^^^^^^
TypeError: BaseEmailMessage.send() missing 1 required positional argument: 'to'
[15/May/2023 21:13:20] "POST /api/auth/users/ HTTP/1.1" 500 128011

my settings:

Python 3.11.2
Django==4.2.1
django-email-log==1.4.0

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'djoser',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'email_log',
    'core',
    'core.auth',
]

EMAIL_LOG_SAVE_ATTACHMENTS = True
EMAIL_BACKEND = 'email_log.backends.EmailBackend'
EMAIL_LOG_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

the letter is written to the database. What am I doing wrong?

**Comment by zykys** [comment]
![image](https://github.com/treyhunner/django-email-log/assets/54861840/67757b19-3513-4f11-9f1c-550eec57b36d)

Yes, the letter arrives

**Comment by spapas** [comment]
@zykys so maybe the error isn't related with this library? From what I understand with the stacktrace you sent, it seems that it tries to send a mail message with no recipients ?

However there are various other libraries in between (djoser, templated_mail) with which i'm not familiar so I'm not really sure what's the problem :(

**Comment by spapas** [comment]
Hello @zykys any updates on this issue? If it isn't related to this package I recommend closing it.

Thank you

**Comment by spapas** [comment]
Closing due to inactivity.
